monitor.bluez.properties = {
    bluez5.enable-sbc-xq = true
    bluez5.enable-volume-sync = true
    bluez5.enable-hw-volume = true
    bluez5.codecs = [ ldac aptx_hd aptx aac sbc_xq sbc ]
    bluez5.default.rate = 48000
}

monitor.bluez.rules = [
    {
        matches = [
            {
                device.name = "~bluez_card.*"
            }
        ]
        actions = {
            update-props = {
                bluez5.auto-connect = [ a2dp_sink ]
                bluez5.hw-volume = [ a2dp_sink ]
            }
        }
    }
]
