context.properties = {
  wireplumber.script-engine = "lua-5.4"
}

context.spa-libs = {
  audio.convert.* = "audioconvert/libspa-audioconvert"
  api.alsa.*      = "alsa/libspa-alsa"
  api.bluez5.*    = "bluez5/libspa-bluez5"
}

context.modules = [
  { name = "libpipewire-module-rt"
    flags = [ "ifexists" "nofail" ]
  }
  { name = "libpipewire-module-protocol-native" }
  { name = "libpipewire-module-client-node" }
  { name = "libpipewire-module-client-device" }
  { name = "libpipewire-module-adapter" }
  { name = "libpipewire-module-metadata" }
  { name = "libpipewire-module-session-manager" }
]

wireplumber.components = [
  { name = "libwireplumber-module-lua-scripting", type = "module" }
  { name = "bluetooth.lua", type = "config/lua"
    provides = "bluetooth.lua"
  }
  { name = "policy.lua", type = "config/lua"
    provides = "policy.lua"
  }
]
